### ISSUE TITLE
Where is "demo" folder?

### ISSUE THREAD

**Issue by hirossyi73** [OfficeDev/office-js-helpers#1]
this repo contains "demo" folder, in this url http://dev.office.com/docs/add-ins/develop/auth-external-add-ins.
"The \demo folder of the repo contains a sample add-in that uses the library to access some popular services including Google, Facebook, and Office 365."
But I can't find it. Where is demo folder??

**Comment by Rick-Kirkham** [comment]
I've removed the inaccurate sentence from the topic. There is not yet any demo incorporated in the library's repo.
