### ISSUE TITLE
Office outlook addin authentication using custom Idserver provider.

### ISSUE THREAD

**Issue by sreddim** [OfficeDev/office-js-helpers#108]
Hi,
We have our custom Identity provider using IdentityServer 3 to authorize our api s.

We are working on OfficeJS Outlook add in created using Aurelia framework.

All our others aurelia client applications works with the authentication by using aurelia-openid-Connect library and we get the token from our identity server authority.

In the same way how can we set up the Office js authentication to talk to out identity server authority and get token  and be able to authorize any external calls made to our Api's.

Are there any examples we can refer to achieve this.

**Comment by LouMM** [comment]
Hi Salini,
Thank you for the great question! Unfortunately we only accept Office JS Helper issues in the repo, but we do have a place to ask questions. 

If you head over to StackOverflow you can tag your questions with officejs and office-addin and this will help flag the appropriate teams to respond. Example [Search here. ](https://stackoverflow.com/search?q=outlook-addin+officejs)

Thank you again for reaching out, and we are excited you are building on Office JS!
