### ISSUE TITLE
IsAddin check fails in Browser, still returns true and uses Dialog framework

### ISSUE THREAD

**Issue by YannickRe** [OfficeDev/office-js-helpers#133]
In a browser the Utilities.isAddin check return true, even when using it outside of Office. This results in the helpers trying to use the Dialog framework to open an authentication window instead of a normal browser popup.

Problematic code:
https://github.com/OfficeDev/office-js-helpers/blob/a7b02821b9ffc9a5d89efaaa2d8f8de701524dc2/src/helpers/utilities.ts#L180

When used in the browser, the `host` property is undefined. This doesn't equal WEB and therefor it is considered being in an AddIn.

Not sure who owns this anymore, so I'm tagging all: @casieber, @Zlatkovsky, @sumurthy & @LouMM

**Comment by jacob-j** [comment]
We are still experiencing this issue on our application. Has the bug returned?
Let me know if you want reproduction steps

**Comment by YannickRe** [comment]
This project is dead, I guess. Nobody bothers to merge PR's or is following up on issues.
Since we invested in using this library, we are building from source (and implemented some other PR's as well) and continue that way until we can strip out this dependency.

**Comment by jacob-j** [comment]
That is sad. Really handy functions for us. Would it be possible for your team to do a fork of this project? Maybe we can help each other out if there are issues and for feature implementation.
