### ISSUE TITLE
Got and solved an Error in Google Chrome Browser

### ISSUE THREAD

**Issue by stotzout** [OfficeDev/office-js-helpers#16]
The state was undefined because in "params" the "state" got saved like this: "result./state"

 `Authenticator.extractParams = function (segment) {
        if (segment == null || segment.trim() === '') {
            return null;
        }
        var params = {}, regex = /([^&=]+)=([^&]*)/g, matchParts;
        while ((matchParts = regex.exec(segment)) !== null) {

            // NEXT LINE GOT ADDED
            if (matchParts[1] === "/state") matchParts[1] = matchParts[1].replace("/", "");
            params[decodeURIComponent(matchParts[1])] = decodeURIComponent(matchParts[2]);
        }
        return params;
    };`

**Comment by WrathOfZombies** [comment]
Thanks for solution. Could you submit a pull request and reference the issue, so that I can test and publish?

**Comment by WrathOfZombies** [comment]
Merged the PR. I actually meant for you to submit the code itself but that's fine, I added it in myself.
Thank you for the contribution 👍
