### ISSUE TITLE
Logoff and force token expiration

### ISSUE THREAD

**Issue by tarunchopra** [OfficeDev/office-js-helpers#24]
How do you logoff and forcefully expire\delete the cached token ?

**Comment by WrathOfZombies** [comment]
We cant technically logoff as not all providers support that implementation. Deleting the token, just removes the token from localStorage but you are still signed in. You will need to write a custom implementation for logout.

With respect to deleting the cached Token, you can do `authenticator.tokens.remove(<name of endpoint>)`

**Comment by WrathOfZombies** [comment]
Also `authenticator.authenticate()` automatically tries to renew the token if it detects that the token has expired.

**Comment by IanVS** [comment]
Note for others who might come across this:

`authenticator.tokens.remove`

is now:

`authenticator.tokens.delete`
