### ISSUE TITLE
How to correctly check the host: Office, Office online and web browser.

### ISSUE THREAD

**Issue by Geraint87** [OfficeDev/office-js-helpers#27]
*** Sorry in advance if this is not the right forum for this question! ***
I would like to detect whether a user has hit the URL of my add-in from a browser, outside of Office and Office online.

I've looked at the utility functions `OfficeHelpers.Utilities.host` and `OfficeHelpers.Utilities.isAddin` but the docs say these will only work after Office.initialize is called. If the URL has been navigated to from outside of an Office client then this won't be the case (?).

So I need to perform the same check as whatever is being done when you get the warning: 
![image](https://cloud.githubusercontent.com/assets/5928208/25845473/ec51271e-34a5-11e7-82ba-86e1ae10d5a6.png)

A simple use of this, would be to direct users to a page that displays explains they cannot access this without loading it as an add-in, and instructions on how to load the add-in etc.

The actual result I am trying to get is to handle both cases as:

1. From within an Office client: "GetData" will return some values and write them to a document.
2. If accessed from a browser: "GetData" will return some value and redirect to a View to display these.

Is there anything wrong with doing this? And how should it be done?

**Comment by Rick-Kirkham** [comment]
@Geraint87 
The best place to ask this question is on StackOverflow. That way other developers who face the question in the future, will have the benefit if the answer. Be sure to tag it "office-js".
