### ISSUE TITLE
connect to sharepoint

### ISSUE THREAD

**Issue by russgove** [OfficeDev/office-js-helpers#31]
Hi, I'm new to office-js. Want to create an outlook addin to talk to sharepoint online. Do you have an example of this?

The doc says:
Add the location of the provider in your AppDomains, example:
    <AppDomain>https://login.windows.net</AppDomain>
    <AppDomain>https://login.microsoftonline.com</AppDomain>

Where do i do that?

**Comment by Rick-Kirkham** [comment]
We don't have a sample of an Outlook add-in that talks to SharePoint. 
The doc is referring to the <AppDomains> section of the add-in manifest. For more information, see [add-in-manifests](https://dev.office.com/docs/add-ins/overview/add-in-manifests).

**Comment by russgove** [comment]
Doe these helpers work with outlook?

**Comment by WrathOfZombies** [comment]
@russgove Yes the helpers work with Outlook Add-ins. But we dont have any Outlook specific code in place. That said, they should help with Authentication.

**Comment by russgove** [comment]
ok, thanks for your help. i will have a go at using the helpless. have been trying to use ADAL, but a steep learning curve! do you guys use that under the covers?

**Comment by WrathOfZombies** [comment]
Nope we don't use ADAL. We have a custom implementation for now due to the fact that we support multiple providers.
