### ISSUE TITLE
Unpin rxjs if possible

### ISSUE THREAD

**Issue by IanVS** [OfficeDev/office-js-helpers#32]
Hi, I see that you've pinned to rxjs version `5.2.0` instead of following semver with something like `^5.2.0`.  I am also using rxjs in my add-in, but at a different (more recent) version.  Because of this, I now have two versions of the same package being bundled.  Is it possible to use a more generous range for `rxjs` in this package?

Thanks!

**Comment by WrathOfZombies** [comment]
@IanVS Sure, we can upgrade the `rxjs` version to the latest minor version. We pinned it for consistency :)

**Comment by WrathOfZombies** [comment]
@IanVS If you'd like please send a PR with the change.

**Comment by IanVS** [comment]
Sure I can send in a PR.  I'd suggest using `yarn.lock` and/or `package.lock` to maintain consistency, which will still allow consumers to use and lock to their own versions.

**Comment by WrathOfZombies** [comment]
We do check in a `yarn.lock` file, so feel free to update that as a part of your PR.

**Comment by IanVS** [comment]
Closed by #33
