### ISSUE TITLE
Entire lodash is being added to dependent projects

### ISSUE THREAD

**Issue by IanVS** [OfficeDev/office-js-helpers#35]
I noticed that my bundle for my add-in has 74kb (gzipped) of lodash in it, even though I don't use lodash in my project.  It seems that it's being pulled in because of `office-js-helpers` and the way that it imports from `lodash`.  

I did a little investigating, and it seems that as of today, it's not super simple to tree-shake lodash with typescript.  https://medium.com/@martin_hotell/tree-shake-lodash-with-webpack-jest-and-typescript-2734fa13b5cd has a good rundown of the challenges and various approaches that can be taken.  It seems that there's upcoming support for a `pure-modules` flag that lodash can/will use, but it doesn't seem to be released in webpack yet: 
 https://twitter.com/jdalton/status/893109185264500737, and it also seems this project uses browserify.  Also, I think you'd need to compile down to ES2015 modules, which I'm not sure all your consumers would be able to handle, so you'd need to perhaps have multiple different builds.

One sure-fire way of ensuring that you do not ship extra code to consumers is to depend on individual lodash modules like `lodash.iserror`.  Then, no matter what kind of build process the consuming add-ins use, they are guaranteed not to get too much code.  

I attempted various approaches like importing from `lodash-es` instead of `lodash`, more focused imports like `import debounce from 'lodash/debounce';`, etc.  But I ran into trouble with either typescript or browserify, neither of which I have much experience with.

So, I guess I would ask if you could find _some_ way to avoid consumers from pulling in all of lodash because of `office-js-helpers`.

**Comment by WrathOfZombies** [comment]
You're right about the increased size and that's something that's started to factor in recently post the 0.7.0 release. I am investigating the cause of the same. Will get back to you. 

Also with webpack I meant, users of the library can use webpack/rollup to tree shake as we do in another project.

**Comment by WrathOfZombies** [comment]
I have a working sample of this. I had to move to a webpack based build system. @IanVS let me know if you'd like to try it out as a beta.

**Comment by IanVS** [comment]
Yeah, that'd be great, thanks.

**Comment by WrathOfZombies** [comment]
@IanVS Here you go: https://unpkg.com/@microsoft/office-js-helpers@0.8.0-beta.1/dist/
and the file being: https://unpkg.com/@microsoft/office-js-helpers@0.8.0-beta.1/dist/office.helpers.js

The new size is 196.32kB uncompressed and 54.01kB compressed.

**Comment by WrathOfZombies** [comment]
@Zlatkovsky FYI

**Comment by TheSamsterZA** [comment]
@WrathOfZombies Do you have a rough idea of when 0.8.0 will be published to npm? Like @IanVS, I am attempting to slim down my dependencies and the entirety of lodash is right up there because `@microsoft/office-js-helpers` pulls it in.

Currently, the latest on npm is 0.7.4.

**Comment by WrathOfZombies** [comment]
@TheSamsterZA, @IanVS: There were some issues found in the beta that I am addressing and I am adding some unit tests. The plan was to launch by New Year's but looks like I am going to push it to the end of Jan.

Sorry for the delay :)

FYI: @Zlatkovsky, @Reezaali
