### ISSUE TITLE
Loading https://...?_host__Info=... disturbs future loading of other pages

### ISSUE THREAD

**Issue by SoftTimur** [OfficeDev/office-js-helpers#37]
Hello,

I just discovered OfficeJSHelpers. I added `console.log("OfficeHelpers.Utilities.host: " + OfficeHelpers.Utilities.host)` and `console.log("OfficeHelpers.Utilities.platform: " + OfficeHelpers.Utilities.platform)` to my website. It works fine, but when I load in a browser `https://localhost:3000/try?_host_Info=excel|web|16.00|en-us|7fe9b4e9-d51e-bea5-d194-c817bc5ed4bc|isDialog#%2Ftry%3F_host_Info=excel%7Cweb%7C16.00%7Cen-us%7C7fe9b4e9-d51e-bea5-d194-c817bc5ed4bc%7CisDialog` (see why I have this url [here](https://stackoverflow.com/questions/45444739/the-url-of-dialog-box-does-not-work-with-angular-bootstrap-infinite-digest-loo)), it considers `EXCEL` as `host` and `OFFICE_ONLINE` as `platform`, and raised an error `Uncaught TypeError: Cannot read property '_appName' of null` in `excel-web-16.00.js`.

What is worse is that, it disturbs the loading of other pages. Now, all the pages like `https://localhost:3000/home` or `https://localhost:3000/try` in a browser returns `EXCEL` as `host` and `OFFICE_ONLINE` as `platform`, and raised an error `Uncaught Error: Sys.ArgumentNullException: Value cannot be null. Parameter name: conversationId` in `excel-web-16.00.js`. The only solution is to clearing browser history data.

I think it is a bug... 

Thank you

**Comment by WrathOfZombies** [comment]
@Zlatkovsky something that you'd want to take a look at.. Are we caching the value of `host` & `platform`? Also why are url parameters even a source for determining paths? I assumed that sessionStorage would provide that information when loading in Office.js
