### ISSUE TITLE
 OfficeHelpers.Utilities.platform returns null in Excel for Windows

### ISSUE THREAD

**Issue by SoftTimur** [OfficeDev/office-js-helpers#38]
Hello,

I load the following page as an Excel add-in in Excel (Office 365 Version 1706) for Windows 7. It shows `EXCEL` as `host`, but `null` as `platform`. I cleared my browser history before the tests...

It seems that for the same code, it showed `PC` yesterday...

Shouldn't it be always `PC` in Excel for Windows?

Thank you

    <html>
        <head>
            <script src="https://appsforoffice.microsoft.com/lib/1/hosted/office.js"></script>
            <script src="https://unpkg.com/@microsoft/office-js-helpers@0.6.3/dist/office.helpers.min.js"></script>
        </head>
        <body>
            <div id="console"></div>
            <script>
                debug("OfficeHelpers.Utilities.host: " + OfficeHelpers.Utilities.host + "<br/>");
                debug("OfficeHelpers.Utilities.platform: " + OfficeHelpers.Utilities.platform);

                function debug(msg) {
                    if (document.getElementById("console") !== null)
                        document.getElementById("console").innerHTML += msg;
                }
            </script>
        </body>
    </html>

**Comment by WrathOfZombies** [comment]
Another host detection problem. Could be related to #37 . @Zlatkovsky thoughts?

**Comment by WrathOfZombies** [comment]
This bug tracks all the issues with identification of hosts. @Zlatkovsky may be we need to revisit the logic for platform detection.

**Comment by WrathOfZombies** [comment]
Closing this as we do not have a consistent repro.
