### ISSUE TITLE
12007 error when using authenticator.authenticate to authenticate to Azure Active Directory

### ISSUE THREAD

**Issue by vjiawon** [OfficeDev/office-js-helpers#4]
I'm receiving an error when calling authenticator.authenticate to authenticate to AAD. If I debug into line 257 of officehelpers.js, I see that the error code is a 12007, which according to the office docs corresponds to multiple dialog boxes opened, but no dialog has been opened. Do I have something wrong with the configuration? I've also added login.windows.net as an app domain to my manifest. My code making the call is below. 
```
            let authenticator = new OfficeHelpers.Authenticator();        
            authenticator.endpoints.registerAzureADAuth("<clientId>", "<tenantName>")
            console.log(authenticator)
            authenticator
                .authenticate(OfficeHelpers.DefaultEndpoints.AzureAD)
                .then(function (token) { console.log("Successfully authenticated", token) })
                .catch(function(error) { console.log("Failed to authenticate", error) })      
```

**Comment by WrathOfZombies** [comment]
@vjiawon Is it possible to send some sample code so that I can re-produce it and test? Your invoke code is correct.

**Comment by vjiawon** [comment]
I did some further debugging and found that the 12007 was a red herring. There was an earlier 12004 that was being swallowed, and the dialog wasn't being disposed, thus subsequent calls to authenticate were rejected with a 12007. The 12004 was caused by an error in the AppDomains elements. Totally on my end :) 

Sorry for the confusion, I'll go ahead and close the issue.
