### ISSUE TITLE
Avoid ugly/scary `X wants to display a new window.`

### ISSUE THREAD

**Issue by IanVS** [OfficeDev/office-js-helpers#40]
We are using this library to handle authentication, but when clicking our `Log in` button, users are shown a `App wants to display a new window.` dialog which they can choose to `Allow` or `Ignore.`  Is there any way to avoid this clunky interaction?  I am concerned that it will cause confusion and abandonment among our users.  

If there's currently no way (it seems there isn't), is there a chance that any changes could be made so that it can be avoided/eliminated?

**Comment by WrathOfZombies** [comment]
@IanVS I am assuming that you are noticing this in Outlook online. If so then I do not think there's a way to go around this for the moment. That said, could you attach a screenshot of the same. 

If not then please let me know where exactly you're seeing this behaviour so that I can help.

@Zlatkovsky I think we need to forward this feedback to the appropriate team.

**Comment by IanVS** [comment]
Thanks for the quick response, @WrathOfZombies.

You're right, I'm seeing it in the web app.  Here's a screenshot:

![image](https://user-images.githubusercontent.com/4616705/29547859-c531838c-86ca-11e7-998e-07c590b6e5a9.png)


I've noticed we're not the only add-in which has this warning.  Salesforce has it as well:

![image](https://user-images.githubusercontent.com/4616705/29547892-f2893a5a-86ca-11e7-8fa4-0c99ac20a29c.png)

**Comment by Zlatkovsky** [comment]
This might technically be "by design", but let me forward this to the appropriate folks on the team.  It's true that the UX/UI could probably be improved...

**Comment by antifun** [comment]
cf. #39, the wish I expressed there is to have a click on "Ignore" be catchable -- I haven't figured out a way to be able to do that.

**Comment by Zlatkovsky** [comment]
Got it, makes sense.  Let me pass on that bit of feedback too, I agree that this feels like it should generate a user-cancelled-this-action event.  For purposes of tracking this request in a visible place, would you mind filing a bug at https://github.com/OfficeDev/office-js/issues ?  And linking to it here?

**Comment by WrathOfZombies** [comment]
Bug will be tracked here: https://github.com/OfficeDev/office-js/issues/13
