### ISSUE TITLE
Dialog error 12002

### ISSUE THREAD

**Issue by GregPartner** [OfficeDev/office-js-helpers#41]
I started new office JS project , the default Word sample, removed all code in Office.initialize, to the point where I only get the following code in Home.js:

`(function () {
    "use strict";

    // The initialize function must be run each time a new page is loaded.
    Office.initialize = function (reason) {
        $(document).ready(function () {
            
            if (OfficeHelpers.Authenticator.isAuthDialog())
                return;

            var authenticator = new OfficeHelpers.Authenticator();
            authenticator.endpoints.registerAzureADAuth('##MYAPPID##', '##MYTENANT##');
            authenticator
                .authenticate(OfficeHelpers.DefaultEndpoints.AzureAD, true)
                .then(function(token) {
                    console.log(token);
                })
                .catch(OfficeHelpers.Utilities.log);
        });
    };
})();`

I know this appId and tenant work fine since I can get the same code to work with ADAL outside office JS, and already ironed out all reply urls and other issues,

The call to _openAuthDialog inside authenticator.authenticate never returns to the promise, and I experience the following error in JS console:

![oauthdialog](https://user-images.githubusercontent.com/30169609/29803557-9cdbd4a2-8c31-11e7-8940-5f5b31467e0a.png)

The Auth popup does appear on top of Web Add-ins, but closes immediately after echoing this error,

Any ideas what is going wrong?

Second question: Am I correct to assume I can use this library for something else than MS Graph, such as  Microsoft Dynamics 365 OData endpoint which supports OAuth 2.0 as  well, or is this just for Office365 and MSGraph?

Thanks

**Comment by Rick-Kirkham** [comment]
12002 means that either the URL that is passed to displayDialogAsync is not a valid URL or the Dialog window was redirected to an invalid URL. (See [Dialog API](https://dev.office.com/docs/add-ins/develop/dialog-api-in-office-add-ins) for more.) Could you use the Fiddler tool to see what the actual URLs are?

**Comment by GregPartner** [comment]
Thanks it works now, 

I used the overrides to change the default redirectUrl and works fine now.
EndpointStorage.prototype.registerAzureADAuth = function (clientId, tenant, overrides)  

I also changed the resource and was able to access my OData feed

Another question: Is there a method to logout to change credentials ?

**Comment by WrathOfZombies** [comment]
@GregPartner There's no default logout implementation as it varies from provider to provider. However there's a logout endpoint for Azure AD that you can hit. You could write a simple method to hit that endpoint and it should log you out.

Also to your earlier question, we do support multiple oauth providers such as Facebook, Google, MSFT, Azure AD out of the box but you could very easily add any provider that works with standards compliant implicit OAuth.

If you do add an additional provider, please do consider sending in a pull request so that everyone can benefit from it.

**Comment by WrathOfZombies** [comment]
@GregPartner Could you tell us what was wrong with the default redirectUrl. It points to `location.origin` and we'd like to understand what was wrong with that as if there's a bug we can fix it and if the error was misleading we can address the error message.

**Comment by GregPartner** [comment]
I'm using this now:

`            var config = {
                clientId: clientId,
                baseUrl: "https://login.windows.net/" + tenant,
                resource: urlD365,
                redirectUrl: redirectUrl
            };
            authenticator.endpoints.registerAzureADAuth(clientId, tenant, config);`

When I comment the config.redirectUrl, I get the above error in the JS console. 
Will send you contact details to profile email, you can contact me on Skype for Business and I'll show you?

**Comment by WrathOfZombies** [comment]
Sure just search for *bhkrish@microsoft.com* on SFB and you can ping me there. Thanks 👍

**Comment by WrathOfZombies** [comment]
@GregPartner you'd need to be looking at https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-integrating-applications#overview-of-the-consent-framework to grant consent. See #45

**Comment by WrathOfZombies** [comment]
@GregPartner I tried out the multi tenant access and you'd need to follow the steps listed here: https://github.com/OfficeDev/office-js-helpers/issues/45#issuecomment-326086032

The earlier method is a sub step that might be unnecessary.

**Comment by GregPartner** [comment]
Looks good on first tenant, I need to be able to logout with another user to test this though, so created new issue / #46 question for logout, Ta
