### ISSUE TITLE
Samples for OfficeJSHelper

### ISSUE THREAD

**Issue by cognologixguru** [OfficeDev/office-js-helpers#42]
Hi,
There should be samples to implement OfficeJSHelper.
Samples Like : Javascript Samples - SPA, C# .NET and NodeJS implementation.

**Comment by cognologixguru** [comment]
Hi,
I have done following code in Home.js. It returns following exception.

Unhandled exception at line 1, column 1149 in https://localhost:44365/office.helpers.min.js
0x800a1391 - JavaScript runtime error: 'Promise' is undefined occurred

[sample.zip](https://github.com/OfficeDev/office-js-helpers/files/1260274/sample.zip)

**Comment by WrathOfZombies** [comment]
Sure will add that to the todo list. @cognologixguru we are also open to contributions if you'd like to do so.

**Comment by WrathOfZombies** [comment]
#44

**Comment by WrathOfZombies** [comment]
Closing this as #44 will track this request.
