### ISSUE TITLE
Authenticator popups Login window but does returns "Token" and "Cached Token" is not found

### ISSUE THREAD

**Issue by cognologixguru** [OfficeDev/office-js-helpers#44]
Authenticator opens up popup window where user can put credentials but **it is not returning any token** as specified.

**Comment by WrathOfZombies** [comment]
Could provide some more information such as console.log errors etc?

**Comment by WrathOfZombies** [comment]
Could you also show some sample code on how you are using the library?

**Comment by WrathOfZombies** [comment]
ping @cognologixguru

**Comment by cognologixguru** [comment]
Hi @WrathOfZombies ,
I am working on samples. Some API issues are there. I will upload few samples soon.

**Comment by WrathOfZombies** [comment]
@cognologixguru here's a sample :) https://gist.github.com/WrathOfZombies/a2c6321a4d7e35c95f87d163ac4cb241
