### ISSUE TITLE
Consent framework?

### ISSUE THREAD

**Issue by magrems** [OfficeDev/office-js-helpers#45]
Does this framework support the implementation of consent framework - https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-integrating-applications#overview-of-the-consent-framework?

I'm experiencing some issues atm, where the consent is not being requested for users from another tenant.

Thanks

**Comment by WrathOfZombies** [comment]
Given that Office Helpers is written for client side code only, you'll need to grant explicit consent to the application's `appId` using the **Grant Permissions** button on the tenant in which you want to use the application.

Once that step is complete, you will be able to sign your users in via the `AzureAD` config flow by setting the `tenant` to the `common`.

**Comment by magrems** [comment]
Can I also ask where exactly is this button? in the Azure portal AAD-app registrations? on the auth popup dialog? elsewhere?

Ta

**Comment by WrathOfZombies** [comment]
@magrems I tried this out and it seems that first you would have to do this: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-integrating-applications#enabling-external-users-to-grant-your-application-access-to-their-resources

Simply follow the instructions on that page. The earlier response was for scenarios where a consent prompt isn't required but I feel that using OfficeHelpers, users will always get a consent prompt and hence that step can be avoided.

**Comment by magrems** [comment]
Thanks, yes, my app is Multi-Tenant enabled already ;)
