### ISSUE TITLE
Logout - Azure AD?

### ISSUE THREAD

**Issue by GregPartner** [OfficeDev/office-js-helpers#46]
Following advice from #41 on logout, I implemented logout of Azure AD using this code:
`function Logout() {`
`    window.location.replace("https://login.microsoftonline.com/" + Tenant + "/oauth2/logout?post_logout_redirect_uri=" + encodeURIComponent(location.origin + location.pathname));`
`}`

This takes me to the Azure AD logout page and seems to be doing logoff...

Then I'm redirected to the post_logout_redirect_uri, which is my main page from SPA office web addins, and the following calls are made again:

`authenticator.endpoints.registerAzureADAuth(...)`
`authenticator.authenticate(OfficeHelpers.DefaultEndpoints.AzureAD)`

This brings up the Azure AD login dialog, which immediately closes and reauthenticates with same user... So I'm unable to login with a different user, and entering a loop of login/logout...

Am I missing something here? Do I need to also clear cookies or localstorage or sessionstorage or else?
Where are the tokens saved? Can I delete them from my code?

Thanks

**Comment by GregPartner** [comment]
Where are the token stored, and can we access those from any place in JS to clear the token store?

Ta

**Comment by WrathOfZombies** [comment]
You can access the local tokens via `authenticator.tokens.get(OfficeHelpers.DefaultEndpoints.AzureAD)`. You can also clear them out via `authenticator.tokens.clear()`.

Also inorder to force a relogin, you can use the force parameter in OfficeHelpers by doing
`authenticator.authentice(OfficeHelpers.DefaultEndpoints.AzureAD, true /* auto clears token and forces reauth */)`

Note: the `force` parameter deletes the local token but doesn't sign out. If you haven't signed out then you'll skill the sign in and consent screen completely.

**Comment by Murugananths** [comment]
Hi Team,

I am getting 12002 dialog error when configuring 3rd party configurations. Can you please suggest any possible causes?
