### ISSUE TITLE
Popup window authentication on IE and Edge is left open instead of closed

### ISSUE THREAD

**Issue by slobshay** [OfficeDev/office-js-helpers#5]
Hi,

Running over IE or Edge has different behavior than running on Firefox or Chrome. While Chrome and Firefox authentication popup window closes once authentication is done, and data is retrieved back in the original window, this is not the case within Internet Explorer or Edge.
IE and Edge popup window won't close which causes retrieved token to remain in new popup window rather than return to original caller window. Once authentication is done, the new popup window is redirected to the "redirection URL" assigned in endpoint.

**Comment by ArjenHartog** [comment]
Hi, already recievedsolution for this? We have the same trouble. Thanks.

**Comment by slobshay** [comment]
Hi, didn't receive a solution yet. I'm not aware of solution availability.
I've moved to use ADAL directly instead.

**Comment by ArjenHartog** [comment]
Hi, thanks, in that case we will look into other approaches too.

**Comment by WrathOfZombies** [comment]
@ArjenHartog, @slobshay  Well the update on it is that there's a Cross Domain postMessage() call issue that needs to be addressed in the underlying API itself. For now I seem to have found a workaround and I am testing that. I'll post back as soon as I have it working.

**Comment by WrathOfZombies** [comment]
Hi @ArjenHartog, @slobshay

Can you guys give the new helpers (v0.4.1) a try and let me know if it works for you. We improved the Add-in detection and so it will resort to using DialogAPI instead of the web browser fallback that was previously there. 

Let me know if you guys have any issues.

**Comment by slobshay** [comment]
Hi @WrathOfZombies,

We switched to use a different library for now, sorry. Will let you know if we plan to move back to helpers.

Thank you.

**Comment by WrathOfZombies** [comment]
Alright i'll close this issue for now. Please re-open it in case you still have problems.

**Comment by stotzout** [comment]
Hi,

i got the same Issues.

If i manually close the Popup by clicking the "x" i get this error:

Ausnahmefehler in Zeile 19, Spalte 68239 in https://localhost:44365/Scripts/Office/1/word-win32-16.01.js
0x800a139e - Laufzeitfehler in JavaScript: Fehler beim Aufrufen der Funktion "close". Fehlercode: 12007.

It says: Cannot call the function "close" in "word-win32-16.01.js"

**Comment by stotzout** [comment]
Solved this Issue by:
https://github.com/OfficeDev/office-js-helpers/issues/16

slobshay ->
"Running over IE or Edge has different behavior than running on Firefox or Chrome. While Chrome and Firefox authentication popup window closes once authentication is done, and data is retrieved back in the original window, this is not the case within Internet Explorer or Edge.
IE and Edge popup window won't close which causes retrieved token to remain in new popup window rather than return to original caller window. Once authentication is done, the new popup window is redirected to the "redirection URL" assigned in endpoint."

I got the same symptoms. And all gone now.

**Comment by WrathOfZombies** [comment]
Just a note here, no matter the implementation, this wont work outside an Add-in in IE11 browser as outside of Add-ins we use a window.popup hack to launch a popup at the login endpoint and complete the authentication. Apart from that, it should work everywhere else consistently.
