### ISSUE TITLE
Authentication fails for web scenario (non-add-in) on IE 11

### ISSUE THREAD

**Issue by Zlatkovsky** [OfficeDev/office-js-helpers#50]
Today's readme says the following:

> Inside of your Office.initialize function add the following check:

    if (OfficeHelpers.Authenticator.isAuthDialog()) return;

> This to inform the Authenticator to automatically close the authentication dialog once the 
    authentication is complete.

This works great for an Office Add-in.  But what about the web scenario?  There the function returns "false" because host is web, and so the dialog flow -- including messaging back to the parent -- fails to complete.

You can actually see this in Script Lab itself, when using it on the web.  Just try signing in to https://script-lab.azureedge.net/

Note that the issue only manifests itself on Internet Explorer (IE 11), not Chrome.

Suggestion:  Rather (or in addition) to having the `isAuthDialog` method (which is actually a bit weird anyway, having it be an `is` but having sideffects), can we have a `closeAuthDialog` method?  Ideally the `authenticate` method would just add some query string parameter (e.g., `?isAuthDialog=true` to the return URI, and read it off from there).  I am also ok with that method requiring a parameter, I can do the query string myself.  But in any case, I need to be able to close the dialog even when running in IE11 in a web-only context.

Thanks!

**Comment by WrathOfZombies** [comment]
@Zlatkovsky, Agreed on the naming. I'll introduce the new signature in 0.8.0 and deprecate the current signature after 2 - 3 releases.

As for the flow itself, I don't see what you hope to accomplish with `isAuthDialog=true`? The dialog closes successfully today and there seems to be some error post that which will debug. Also there's no messaging back happening when its in only Web mode in IE 11. When `isAuthDialog` detects web mode, it just decides to create a new popup and constantly poll the popup till its back on the same domain.

**Comment by WrathOfZombies** [comment]
@Zlatkovsky After thinking this through more carefully, I realize the current name is the best possible name that I can provide. But before I discuss that, the error that you are facing isn't related to `messageParent` and the host detection is working fine. Its an IE11 issue that I am trying to work around and will fix it soon.

As for the name itself. The idea behind the name is as follows:

```javascript
if(Authenticator.isAuthDialog()) {
  // Then we know for sure that this code is running inside of a dialog (irrespective of an Office dialog, teams dialog or web popup)
 // Allow the developer to run the custom code here or completely stop execution
}

// This code will only be run inside of the main Add-in unless the developer hasn't stopped execution inside of a dialog. If so then both pieces of code will be run.
```

**Comment by Zlatkovsky** [comment]
Bhargav, I agree that as single call that both dispatches and returns a result, it's hard to make that API name better.  But what if you have something like this:

    let initializeResult = Authenticator.initializeIfRelevant();
    if (initializeResult.isAuthDialog) {
        // ...
        return;
     }

Which of course can be simplified to

    if (Authenticator.initializeIfRelevant().isAuthDialog) {
        // ...
        return;
     }

And you can probably come up with a better name for `initializeIfRelevant` (including just `initialize()`), though I think the "is relevant" piece is also important to convey.

What do you think about that?

**Comment by WrathOfZombies** [comment]
@Zlatkovsky Would you like to test out https://unpkg.com/@microsoft/office-js-helpers@0.8.0-beta.4/dist/office.helpers.js. This addresses all the authentication issues faced in IE11

**Comment by WrathOfZombies** [comment]
ping @Zlatkovsky

**Comment by Zlatkovsky** [comment]
@WrathOfZombies , I tried integrating "0.8.0-beta.4" into Script Lab just now.  I can't speak to the authentication issues, but it does break a bunch of other stuff (editor doesn't fully load; get an "Unable to get property 'lastUpdatedText' of undefined or null reference, which is coming out of Script Lab code, but is presumably being caused by some change in the Office.js helpers).

I haven't had a chance to debug it, but when I rolled back to 0.7.4 things were good again, and when I rolled forward to 0.8.0-beta.4, things were broken again.  You can try it yourself simply by checking out the latest version of Script Lab, master branch (or others...) and first seeing that the site works in IE in the old version, and then fails with the new OfficeJsHelpers version.

(BTW, it fails in chrome as well, without a console error, but with same effect of the site becoming non-usable; perhaps it's some observable is breaking, and the buttons no longer respond after that).

**Comment by Zlatkovsky** [comment]
BTW, is there a way (a tag?) by which I could view the diff between 0.8.0-beta.4 and 0.7.4?

**Comment by WrathOfZombies** [comment]
Here's the delta but its quite large as there have been many changes from 0.7 to 0.8...

https://github.com/OfficeDev/office-js-helpers/compare/master...bhkrish/revamped-dialog-flow

**Comment by ChobiJava** [comment]
Still seeing the problem that the Dialog won't close correctly in IE11 with 0.8.0-beta.4.

It seems to lie in that even though I'm running IE11, ` Utilities.isAddin()` still returns true in `Dialog.close().`

**Comment by WrathOfZombies** [comment]
@ChobiJava 

So in the beta, the dialog problem with IE11 is solved by using `localStorage`. I have an interval tick to check if a particular unique localStorage item has been set and if so extract it and get the value from there. When running the beta and launching the dialog, after the redirection is complete, please check if the localStorage contains this key: `VGVtcG9yYXJ5S2V5Rm9yT0pIQXV0aA==`?

Also with respect to the lie, can you tell me the value of `Utilities.host` & `Utilities.platform` as that would help debug further?

**Comment by ChobiJava** [comment]
@WrathOfZombies 

Yeah, I found the reference to that key in the code while debugging. The value of the key is never set because of this codeblock

![image](https://user-images.githubusercontent.com/8879658/33709060-7fbb6a36-db3c-11e7-810a-a46c1d376b34.png)


For the `Utilities.host` it returns `OUTLOOK`, while `Utilities.platform` returns `OFFICE_ONLINE`.

**Comment by WrathOfZombies** [comment]
Then that is expected. As we want to use Outlook's Add-in dialog. That said I am going to raise this as a platform bug as many folks have reported that the dialog doesn't close in IE11.

**Comment by WrathOfZombies** [comment]
Please try the latest version and let me know if you are still seeing issues. @ChobiJava 

[Get the latest from here](https://unpkg.com/@microsoft/office-js-helpers)

**Comment by ChobiJava** [comment]
The code seem to execute correctly @WrathOfZombies , but unfortunately as stated in [this new issue](https://github.com/OfficeDev/office-js-helpers/issues/65) the configuration for the endpoint is returned rather than the actual token.
