### ISSUE TITLE
Get User Name?

### ISSUE THREAD

**Issue by ostorefice** [OfficeDev/office-js-helpers#51]
Hi office-js-helpers,

Great tool, I just can't figure out where to get the username after receiving the token?
I know ADAL.js gives us the username, but can't find it in this lib.

Any advice?

**Comment by WrathOfZombies** [comment]
@ostorefice Thanks 👍 

There's no way to get user name in this library as we don't control the scope/API implementations of each of the Auth providers. It would add additional maintenance costs and hence I suggest using the Graph API to get that information with the token you obtained.

See more info here: https://developer.microsoft.com/en-us/graph/

Here's a sample on how to use Office Helpers with graph: https://github.com/microsoftgraph/javascript-officeuifabric-peoplepicker-sample/blob/master/PeoplePicker.html#L163

**Comment by azolson** [comment]
If, by username you mean the UPN then this is one of the returned values (I'm using the /me endpoint when querying msft graph)

I'm using react, but the following code is probably quite obvious, and provides me with the UPN (the token's scope used for this request is https://graph.microsoft.com/User.Read):

```
export function getMicrosoftUserProfile(token){
    return function(dispatch){
        request
            .get(`${constants.MSFT_DATA_API}/me/`)
            .set('Accept', 'application/json')
            .set('Authorization', `Bearer ${token.access_token}`)
        .then(
            res => {
                if (res.status >= 200 && res.status < 300) {
                    dispatch(setUserInformation(res.body))
                    console.log(res.body)
                }
            }
        )
        .catch((err) => {
            console.log(err.status + ': ' + err.response)
          })
    }
}

```

returned values:
```
businessPhones : []
displayName : "Marvin Martian"
givenName : "Marvin"
id : "4b60d56e-4edd-4b4c-873a-f0e6d1112345"
jobTitle : "Chief Technology Officer"
mail : "marvin@thisis.mars"
mobilePhone : "+44 12345656"
officeLocation : null
preferredLanguage :"en-GB"
surname : "Martian"
userPrincipalName : "marvin@thisis.mars"
```

**Comment by WrathOfZombies** [comment]
@azolson yes the username would be the UPN.
