### ISSUE TITLE
Opening SSO popup fails

### ISSUE THREAD

**Issue by AlexUrbanAc** [OfficeDev/office-js-helpers#52]
I got the SSO login working in Chrome with popup, and now I am trying the Outlook plugin against Outlook 2016 (EXE version 16.0.8431.2107). When I open F12 Developer Tools and call 

Authenticator.authenticate("AzureAD")

I get

Script 5022: Die Domäne der URL ist nicht im "AppDomains"-Element im Manifest enthalten.

but the endpoint's baseUrl is

https://login.windows.net/09265c06-...-1c39

and my AddIn's AppDomains are (copied from a Microsoft list):

``  <AppDomains>
	<AppDomain>api.login.microsoftonline.com</AppDomain>
	<AppDomain>clientconfig.microsoftonline-p.net</AppDomain>
	<AppDomain>device.login.microsoftonline.com</AppDomain>
	<AppDomain>hip.microsoftonline-p.net</AppDomain>
	<AppDomain>hipservice.microsoftonline.com</AppDomain>
	<AppDomain>login.microsoft.com</AppDomain>
	<AppDomain>login.microsoftonline.com</AppDomain>
	<AppDomain>logincert.microsoftonline.com</AppDomain>
	<AppDomain>loginex.microsoftonline.com</AppDomain>
	<AppDomain>login-us.microsoftonline.com</AppDomain>
	<AppDomain>login.microsoftonline-p.com</AppDomain>
	<AppDomain>nexus.microsoftonline-p.com</AppDomain>
	<AppDomain>stamp2.login.microsoftonline.com</AppDomain>
	<AppDomain>login.windows.net</AppDomain>
  </AppDomains>

I now found this comment by a Microsoft employee:

https://stackoverflow.com/questions/45438165/domain-is-not-trusted-using-word-2016-while-opening-dialog-to-remote-url

> The page, controller method, or other resource that is passed to the displayDialogAsync method must be in the same domain as the host page.

It seems that you call displayDialogAsync with the remote URL; is that correct, and did that work for anyone at all?

**Comment by WrathOfZombies** [comment]
Yes it is correct. And yes it has worked for folks including myself. That said, can you send me a repro project so that I can run it and see what's happening.

**Comment by WrathOfZombies** [comment]
@AlexUrbanAc Alternatively could you try this beta version and tell me if it works for you? https://unpkg.com/@microsoft/office-js-helpers@0.8.0-beta.4/dist/office.helpers.js

**Comment by dong-gyun** [comment]
I tried it with beta version. when try in ie11, this version occur error Array.from and Map initialization. when test in chrome, it work wall.

**Comment by WrathOfZombies** [comment]
Yes you need to include `core-js` library. Its listed as a per-requisite for this library. You can get it from https://unpkg.com/core-js/client/core.min.js

**Comment by dong-gyun** [comment]
Thank you very much. I include core-js in my project, so it works well in ie11.
