### ISSUE TITLE
newWindowNotificaiton dialog

### ISSUE THREAD

**Issue by Mangemannen66** [OfficeDev/office-js-helpers#56]
Hi!

Is there any easy task to get past the "issue" of having to approve opening of a new window? 

![newwindownotification](https://user-images.githubusercontent.com/6208986/32000441-fedfbcf8-b996-11e7-9dbe-7d9adf09ecc1.png)
Thanks in advance
(The misspelling -> newWindowNotificaiton is actually copied from the webinspector)

**Comment by WrathOfZombies** [comment]
@Mangemannen66 Nope sorry at this moment this is by design.

FYI: @sumurthy, @Zlatkovsky, more feedback on this issue.

**Comment by Zlatkovsky** [comment]
Noting that the question has been moved to StackOverflow:  https://stackoverflow.com/questions/46928205/how-to-automaticly-approve-opening-of-new-window-for-authenticating.  Thanks, @Mangemannen66 (though please see my comment there)
