### ISSUE TITLE
Need to increase the oauth2 token expiration

### ISSUE THREAD

**Issue by realpasro09** [OfficeDev/office-js-helpers#57]
When I trying to authenticate using **registerMicrosoftAuth** I notice that the token expire by default in 3600 seconds. 

I was reviewing the library and I'm seeing a method **setExpiry** inside TokenStorage class
[https://github.com/OfficeDev/office-js-helpers/blob/4687cc5320b934b464a5fcd0ed648a031e9e07fc/src/authentication/token.manager.ts#L42-L47](https://github.com/OfficeDev/office-js-helpers/blob/4687cc5320b934b464a5fcd0ed648a031e9e07fc/src/authentication/token.manager.ts#L42-L47)

Is there any easy way to set the desired expiration date before request the authenticate method?

This is how I'm requesting the token:

```
OutlookAuthenticate() {
    const authenticator = new Authenticator();
    authenticator.endpoints.registerMicrosoftAuth(microsoftApplicationClientId, {
      scope: 'User.Read User.ReadBasic.All Contacts.Read Contacts.ReadWrite',
    });
    return authenticator.authenticate(DefaultEndpoints.Microsoft)
      .then(this.parseResponse);
  }
```

**Comment by WrathOfZombies** [comment]
That method wasn't exposed as I wished to renew the token as soon as it expires. That said, today if you want to modify the expiration then you can do the following:

```javascript
    const authenticator = new Authenticator();
    var token = authenticator.tokens.get(DefaultEndpoints.Microsoft);
    // set the token.expires_in to a time in seconds
    authenticator.tokens.insert(DefaultEndpoints.Microsoft, token);
```

When the set expiry logic kicks in, it will first try and read if there's a valid expiration and then go ahead and determine the expiration date (expires_at) which then let's the authenticator determine if a new login is required.
