### ISSUE TITLE
office-js-helper

### ISSUE THREAD

**Issue by davallen** [OfficeDev/office-js-helpers#63]
I have been trying to implement a custom app in Teams. As part of the app i am making a call to an external web API. I am trying to use the office-js-helpers library to obtain a id_token, but I am seeing that the _handleTokenResult does not handle the id_token responsetype result, even though the library allows for providing a responseType. Am I missing something obvious? Or is not supporting this auth pattern intentional within the library. Also, i am using this library to handle the team situation with the popup as opposed to hidden IFRAME that the adal.js library uses.

**Comment by WrathOfZombies** [comment]
@davallen Let me take a look and get back to you on this.

**Comment by WrathOfZombies** [comment]
@davallen Could you provide me a sample solution where you are seeing the problem so that I can get a clear repro?
