### ISSUE TITLE
container params colliding for endpoints and token storage

### ISSUE THREAD

**Issue by ayushsood** [OfficeDev/office-js-helpers#65]
See:
  - https://github.com/OfficeDev/office-js-helpers/blob/master/src/authentication/token.manager.ts#L36
  - https://github.com/OfficeDev/office-js-helpers/blob/master/src/authentication/endpoint.manager.ts#L63

If you set up an OAuth endpoint via:

```js
const authenticator = new Authenticator();
authenticator.endpoints.add(OAUTH_CLIENT.clientName, {
  clientId: OAUTH_CLIENT.clientId,
  baseUrl: OAUTH_CLIENT.baseUrl,
  authorizeUrl: OAUTH_CLIENT.authorizeUrl,
  responseType: 'token'
});
```

And try to print out a token (should be `null`), via:
```js
console.log(authenticator.tokens.get(OAUTH_CLIENT.clientName));
```

You get the endpoint configuration back.

Suggested fix:
Change line 36 in `token.manager.ts` to `super('OAuth2Tokens', storageType);`

**Comment by WrathOfZombies** [comment]
There was a bug in the container name. This has been addressed recently. I'll push a new update to the library. 

Thanks

**Comment by ayushsood** [comment]
@WrathOfZombies it would be helpful if the issues were kept open until the fix has been merged in and pushed to the npm repo. Thanks!

**Comment by WrathOfZombies** [comment]
Fixed in https://unpkg.com/@microsoft/office-js-helpers@1.0.1/dist/office.helpers.js
