### ISSUE TITLE
excel add-in opens new tab in chrome instead of pop-up

### ISSUE THREAD

**Issue by ayushsood** [OfficeDev/office-js-helpers#66]
I'm using a Mac - behavior is as expected if opened via Chrome itself (opens a pop-up), but when opened as an add-in within excel, it instead opens a new tab in Chrome preventing the user from completing the sign-in process.

Perhaps related to https://github.com/firebase/firebase-js-sdk/issues/63 (though I'm using Chrome 64, which should be fixed)

Also is there any documentation on how to debug an add-in when it's opened within an Office product?

**Comment by WrathOfZombies** [comment]
@ayushsood I see that you managed to resolve the issue. Is there an action item here?

**Comment by daniel-white** [comment]
@WrathOfZombies  i dont see any resolution here. this is happening in word too which I'm guessing is realted to OfficeDev/office-js#73
