### ISSUE TITLE
What reply URL to configure to make it work with native Outlook?

### ISSUE THREAD

**Issue by binarykitchen** [OfficeDev/office-js-helpers#86]
Developed an add-in and tried to test it on native Outlook for Mac OS.

But upon authentication on login.microsoftonline.com I see following error:
![screen shot 2018-05-14 at 17 13 50](https://user-images.githubusercontent.com/177641/39979387-40014aac-579a-11e8-9ce6-46b4d23af6bd.png)

Here is what I have configured under apps.dev.microsoft

![screen shot 2018-05-14 at 17 15 04](https://user-images.githubusercontent.com/177641/39979424-6820280a-579a-11e8-980d-671430efc1c9.png)

Any clues?

**Comment by elegault** [comment]
Try adding that URL to your add-in's manifest:

`  <AppDomains>
    <AppDomain>https://localhost:3443</AppDomain>
  </AppDomains>`

**Comment by binarykitchen** [comment]
yes, this did it
