### ISSUE TITLE
The extension custom properties could not be saved

### ISSUE THREAD

**Issue by binarykitchen** [OfficeDev/office-js-helpers#97]
Whenever I have a message in my inbox, process it for first time and attempt to save custom properties, this error comes up

```
{"WasSuccessful":false,"ErrorMessage":"The extension custom properties could not be saved."}
```

No idea why. Doesn't say much. And I've loaded the custom properties before without any errors. And more weird, this only happens for messages in Inbox. Not when messages are in other folders, there saving custom properties works fine.

**Comment by LouMM** [comment]
This issue is related to a problem in Office.js for Outlook around Custom Properties and doesn't seem related to Office-js-helpers. Please create an issue in the Office.js repo and tag it with Outlook to have it reviewed by that team. https://github.com/OfficeDev/office-js/issues
